# Generated by Django 4.2.1 on 2023-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_csvfile_rename_columnname_chartdata_column_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='acitvated',
            new_name='activated',
        ),
    ]
