# Generated by Django 4.2.1 on 2023-05-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_remove_chartdata_column_names_data_chart_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chart_data_chart', to='graphs.chartdata'),
            preserve_default=False,
        ),
    ]
