# Generated by Django 4.2.1 on 2023-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0008_remove_data_chart_chart_chart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
