# Generated by Django 4.2.1 on 2023-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_alter_data_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
