# Generated by Django 4.2.1 on 2023-05-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0010_alter_data_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='label1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='label2',
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
                ('chart_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='graphs.chartdata')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_data', to='graphs.label'),
        ),
    ]
