# Generated by Django 4.2.1 on 2023-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0011_remove_data_label1_remove_data_label2_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='rows',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
