# Generated by Django 4.2.1 on 2023-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0012_chartdata_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='rows',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
