# Generated by Django 4.2.1 on 2023-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0014_remove_chartdata_rows_row_data_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='row',
        ),
        migrations.AddField(
            model_name='chartdata',
            name='rows',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
