# Generated by Django 4.2.1 on 2023-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0016_remove_chartdata_rows_row_data_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='ChartData',
            new_name='chart_data',
        ),
    ]
