# Generated by Django 4.2.1 on 2023-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0017_rename_chartdata_row_chart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='row_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
